name: workflow_test alt.1
# -- Workflow för test av applikation körs när en pull request mot main utförs (CI). Körs på windows.

on:
  pull_request:
    branches: 
      - main
      
jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'
      - name: Build
        run: |
          set CGO_ENABLED=0 
          set GOOS=windows 
          set GOARCH=amd64 
          go build -o endpoint -o build/endpoint main.go
      - name: Test
        run: go test ./...
